<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EmployeeList.aspx.cs" Inherits="EmployeeManagement.EmployeeList" %>

<!DOCTYPE html>

<html>
<head runat="server">
    <title>Employee List</title>

    <style>
        body {
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f4f6f9;
        }

        .container {
            width: 90%;
            margin: 40px auto;
        }

        .header {
            background-color: #123c69;
            color: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
        }

        .table-box {
            background-color: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 3px 10px #ddd;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            background-color: #1769aa;
            color: white;
            padding: 12px;
            text-align: left;
        }

        td {
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }

        .back-btn {
            display: inline-block;
            margin-top: 20px;
            padding: 10px 18px;
            background-color: #123c69;
            color: white;
            text-decoration: none;
            border-radius: 6px;
        }
    </style>
</head>

<body>

<form id="form1" runat="server">

    <div class="container">

        <div class="header">
            <h1>Employee List</h1>
            <p>View all employee information</p>
        </div>

        <div class="table-box">
            <div style="margin-bottom:20px;">

    <asp:TextBox ID="txtSearch" runat="server"
        placeholder="Search Employee ID or Name"
        Width="250px">
    </asp:TextBox>

    <asp:Button ID="btnSearch" runat="server"
        Text="Search"
        OnClick="btnSearch_Click" />

    <asp:Button ID="btnShowAll" runat="server"
        Text="Show All"
        OnClick="btnShowAll_Click" />

</div>

           <asp:GridView ID="gvEmployees"
    runat="server"
    AutoGenerateColumns="true"
    DataKeyNames="EmployeeID"
    AutoGenerateEditButton="true"
    AutoGenerateDeleteButton="true"
    OnRowEditing="gvEmployees_RowEditing"
    OnRowCancelingEdit="gvEmployees_RowCancelingEdit"
    OnRowUpdating="gvEmployees_RowUpdating"
    OnRowDeleting="gvEmployees_RowDeleting"
    Width="100%"
    CellPadding="10"
    GridLines="Horizontal"
    HeaderStyle-BackColor="#1769aa"
    HeaderStyle-ForeColor="White"
    RowStyle-BackColor="White">
</asp:GridView>
            <a href="Employees.aspx" class="back-btn">
    + Add New Employee
</a>

            <a href="Employee Management.aspx" class="back-btn">
                ← Back to Dashboard
            </a>

        </div>

    </div>

</form>

</body>
</html>